name: Generate Snake Game Animation

on:
  # Triggers the workflow on push to the main branch or every day at midnight
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  generate-snake:
    name: Generate Snake Game
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Generate the Snake Game SVG animation
      - name: Generate Snake Game animation
        uses: Platane/snk@v2.0.2
        with:
          github_user_name: ${{ github.repository_owner }}
          output: dist/snake.svg

      # Step 3: Commit and push the updated README.md (if changes exist)
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Snake Game animation in README"
          branch: main

      # Step 4: Add the Snake Game animation to the README.md
      - name: Update README with Snake animation
        run: |
          echo "![Snake Game Animation](dist/snake.svg)" >> README.md
